-- MySQL Script generated by MySQL Workbench
-- Thu Apr 24 01:10:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`attribute_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`attribute_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`attribute_category` (
  `id_attribute_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(225) NULL,
  PRIMARY KEY (`id_attribute_category`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`attribute_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`attribute_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`attribute_type` (
  `id_attribute_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id_attribute_type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brand` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `website` VARCHAR(255) NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id_brand`),
  CONSTRAINT `fk_brand_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`brand` (`name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_brand_product_idx` ON `mydb`.`brand` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`color` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`color` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `hex value` VARCHAR(7) NULL,
  PRIMARY KEY (`id_color`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`color` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `brand_id` INT NOT NULL,
  `product_category_id` INT NOT NULL,
  `base_price` DECIMAL(10,2) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`product_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_attribute` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`product_attribute` (
  `id_product_attribute` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL,
  `attribute_type_id` INT NULL,
  `value` VARCHAR(100) NULL,
  PRIMARY KEY (`id_product_attribute`),
  CONSTRAINT `fk_product_attribute_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_attribute_type`
    FOREIGN KEY (`attribute_type_id`)
    REFERENCES `mydb`.`attribute_type` (`id_attribute_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_product_attribute_product_idx` ON `mydb`.`product_attribute` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_product_attribute_type_idx` ON `mydb`.`product_attribute` (`attribute_type_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`product_category` (
  `id_product_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id_product_category`),
  CONSTRAINT `fk_product_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`product_category` (`name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_product_category_product1_idx` ON `mydb`.`product_category` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_image` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`product_image` (
  `id_product_image` INT NOT NULL DEFAULT Unique identifier,
  `product_id` INT NOT NULL DEFAULT FK to product.id,
  `image_url` VARCHAR(225) NOT NULL DEFAULT 'Stores image file path or URL',
  `alt_text` VARCHAR(225) NULL DEFAULT '(optional) Alt description for image',
  PRIMARY KEY (`id_product_image`),
  CONSTRAINT `fk_product_image_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_product_image_product_idx` ON `mydb`.`product_image` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`product_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_item` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`product_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `sku` VARCHAR(50) NULL,
  `quantity_in_stock` INT NOT NULL,
  `price_override` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_item_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_item_variation`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`product_variation` (`id_product_variation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_product_item_product_idx` ON `mydb`.`product_item` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`product_variation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_variation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`product_variation` (
  `id_product_variation` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `size_option_id` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id_product_variation`),
  CONSTRAINT `fk_product_variation_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_variation_color`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`color` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_product_variation_product_idx` ON `mydb`.`product_variation` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_product_variation_color_idx` ON `mydb`.`product_variation` (`color_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`size_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`size_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`size_category` (
  `id_size_category` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id_size_category`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`size_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`size_option` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`size_option` (
  `id_size_option` INT NOT NULL AUTO_INCREMENT,
  `size_label` VARCHAR(50) NOT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id_size_option`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
