-- MySQL Script generated by MySQL Workbench
-- Generated for ecommerce database

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8;
USE `ecommerce`;

-- Attribute Category
CREATE TABLE IF NOT EXISTS `attribute_category` (
  `id_attribute_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(225),
  PRIMARY KEY (`id_attribute_category`)
) ENGINE = InnoDB;

-- Attribute Type
CREATE TABLE IF NOT EXISTS `attribute_type` (
  `id_attribute_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255),
  PRIMARY KEY (`id_attribute_type`)
) ENGINE = InnoDB;

-- Brand
CREATE TABLE IF NOT EXISTS `brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT,
  `website` VARCHAR(255),
  PRIMARY KEY (`id_brand`)
) ENGINE = InnoDB;

-- Color
CREATE TABLE IF NOT EXISTS `color` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `hex_value` VARCHAR(7),
  PRIMARY KEY (`id_color`)
) ENGINE = InnoDB;

-- Product
CREATE TABLE IF NOT EXISTS `product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `brand_id` INT NOT NULL,
  `product_category_id` INT NOT NULL,
  `base_price` DECIMAL(10,2) NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`brand_id`) REFERENCES `brand`(`id_brand`),
  FOREIGN KEY (`product_category_id`) REFERENCES `product_category`(`id_product_category`)
) ENGINE = InnoDB;

-- Product Category
CREATE TABLE IF NOT EXISTS `product_category` (
  `id_product_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`id_product_category`)
) ENGINE = InnoDB;

-- Product Image
CREATE TABLE IF NOT EXISTS `product_image` (
  `id_product_image` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `image_url` VARCHAR(225) NOT NULL,
  `alt_text` VARCHAR(225),
  PRIMARY KEY (`id_product_image`),
  FOREIGN KEY (`product_id`) REFERENCES `product`(`id`)
) ENGINE = InnoDB;

-- Product Item
CREATE TABLE IF NOT EXISTS `product_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `sku` VARCHAR(50),
  `quantity_in_stock` INT NOT NULL,
  `price_override` DECIMAL(10,2),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`product_id`) REFERENCES `product`(`id`)
) ENGINE = InnoDB;

-- Size Category
CREATE TABLE IF NOT EXISTS `size_category` (
  `id_size_category` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`id_size_category`)
) ENGINE = InnoDB;

-- Size Option
CREATE TABLE IF NOT EXISTS `size_option` (
  `id_size_option` INT NOT NULL AUTO_INCREMENT,
  `size_label` VARCHAR(50) NOT NULL,
  `category_id` INT,
  PRIMARY KEY (`id_size_option`),
  FOREIGN KEY (`category_id`) REFERENCES `size_category`(`id_size_category`)
) ENGINE = InnoDB;

-- Product Variation
CREATE TABLE IF NOT EXISTS `product_variation` (
  `id_product_variation` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `size_option_id` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id_product_variation`),
  FOREIGN KEY (`product_id`) REFERENCES `product`(`id`),
  FOREIGN KEY (`color_id`) REFERENCES `color`(`id_color`),
  FOREIGN KEY (`size_option_id`) REFERENCES `size_option`(`id_size_option`)
) ENGINE = InnoDB;

-- Product Attribute
CREATE TABLE IF NOT EXISTS `product_attribute` (
  `id_product_attribute` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT,
  `attribute_type_id` INT,
  `value` VARCHAR(100),
  `attribute_category_id` INT,
  PRIMARY KEY (`id_product_attribute`),
  FOREIGN KEY (`product_id`) REFERENCES `product`(`id`),
  FOREIGN KEY (`attribute_type_id`) REFERENCES `attribute_type`(`id_attribute_type`),
  FOREIGN KEY (`attribute_category_id`) REFERENCES `attribute_category`(`id_attribute_category`)
) ENGINE = InnoDB;

-- Reset SQL modes
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
